runtime: php72

runtime_config:
  document_root: public

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:MvepBNgyWKsrjI3jr4/PRSN6PLC3DuxiUZk28otK1L8=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_CONNECTION: mysql
  DB_HOST: localhost
  DB_PORT: 3306
  DB_DATABASE: laravel_gamebook
  DB_USERNAME: root
  DB_PASSWORD: password
  ## for MYSQL, use DB_SOCKET:
  DB_SOCKET: "/cloudsql/laravel-gamebook:asia-east1:laravel-gamebook"

  FILESYSTEM_DRIVER: gcs
  GOOGLE_CLOUD_PROJECT_ID: laravel-gamebook
  GOOGLE_CLOUD_STORAGE_BUCKET: laravel-gamebook.appspot.com
